### ISSUE TITLE
you can get inspired by ar-php or contribute to it

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [ara-lang/ara-lang.io#1]
Hello @azjezz 

I like you are doing something related to Arabic and PHP. 

you can watch this library to get inspired from or to contribute to: https://github.com/khaled-alshamaa/ar-php

have a nice day.

**Comment by azjezz** [comment]
Hey @WatheqAlshowaiter, this project has nothing to do with Arabic, this is a programming language ^^" 

see https://github.com/ara-lang/.github/blob/main/profile/README.md for more information.

**Comment by WatheqAlshowaiter** [comment]
I didn't know :) Good luck.
