### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by nhedger** [ara-lang/ara-lang.io#11]
This issue tracks the implementation of code highlighting in the documentation.

Vitepress uses [Shiki](https://github.com/shikijs/shiki) to highlight code and it is possible to add support for our own language using a `tmLanguage` file.

There is a fair chance that [ara-lang/highlighting](https://github.com/ara-lang/highlighting/tree/main/syntaxes) already provides the necessary building blocks for this.

Ref: https://github.com/shikijs/shiki/blob/main/docs/languages.md#supporting-your-own-languages-with-shiki

**Comment by azjezz** [comment]
Yes, but we don't want to hard code it, maybe we can fetch it using raw `https://raw.githubusercontent.com/ara-lang/highlighting/main/syntaxes/ara.json` url?

**Comment by nhedger** [comment]
Agreed. I'll look into this.

**Comment by nhedger** [comment]
I've opened a PR on Shiki's repository. Let's see if it gets accepted.

https://github.com/shikijs/shiki/pull/407

**Comment by nhedger** [comment]
The PR has been accepted and merged @azjezz.
